# ADS1002 Project Report Notebook Template

## 1. Title, Members & Theme

Provide the project title, list members of the group and overall theme or context. Include dataset source and domain.

## 2. Introduction & Research Questions

Introduce the problem, motivation, and objectives. Clearly list the research questions or hypotheses.

## 3. Data Dictionary

List each feature/column, its type, and meaning. Helpful for readers unfamiliar with the dataset.

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

ICU = pd.read_csv("Preprocessed ICU data.csv")
ICU.head()

,RecordID,Age,Gender,Height,ICUType2,ICUType3,ICUType4,Mean_Weight.x,Mean_GCS.x,Mean_HR.x,...,Max_ALT.y,Max_AST.y,Max_Bilirubin.y,Max_Lactate.y,Max_Cholesterol.y,Max_TroponinI.y,Max_TroponinT.y,SAPS.I,SOFA,In.hospital_death
0,132543,68,1.0,180.300000,0,1,0,84.600000,14.888889,72.971429,...,12.000000,15.000000,0.200000,2.395461,156.842105,7.132683,1.114629,7,1,0
1,132545,88,0.0,169.787227,0,1,0,83.054136,15.000000,79.520000,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,17,2,0
2,132547,64,1.0,180.300000,0,0,0,114.000000,8.333333,81.318182,...,60.000000,162.000000,0.400000,2.395461,212.000000,1.300000,1.114629,14,11,0
3,132551,78,0.0,162.600000,0,1,0,48.400000,13.250000,78.125000,...,46.000000,82.000000,0.300000,2.300000,156.842105,3.500000,1.114629,19,8,1
4,132554,64,0.0,169.787227,0,1,0,60.700000,15.000000,129.363636,...,189.169186,260.323666,1.979557,2.395461,156.842105,7.132683,1.114629,11,0,0

In [39]:
ICU.shape

(1474, 232)

In [40]:
ICU.isna().sum()

RecordID             0
Age                  0
Gender               0
Height               0
ICUType2             0
                    ..
Max_TroponinI.y      0
Max_TroponinT.y      0
SAPS.I               0
SOFA                 0
In.hospital_death    0
Length: 232, dtype: int64

In [41]:
ICU.describe

<bound method NDFrame.describe of       RecordID  Age  Gender      Height  ICUType2  ICUType3  ICUType4  \
0       132543   68     1.0  180.300000         0         1         0
1       132545   88     0.0  169.787227         0         1         0
2       132547   64     1.0  180.300000         0         0         0
3       132551   78     0.0  162.600000         0         1         0
4       132554   64     0.0  169.787227         0         1         0
...        ...  ...     ...         ...       ...       ...       ...
1469    142661   89     1.0  177.800000         0         0         1
1470    142662   86     1.0  162.600000         0         1         0
1471    142664   51     0.0  169.787227         0         0         1
1472    142665   70     0.0  169.787227         0         0         1
1473    142671   37     1.0  169.787227         0         1         0

      Mean_Weight.x  Mean_GCS.x   Mean_HR.x  ...    Max_ALT.y    Max_AST.y  \
0         84.600000   14.888889   72.971429  ...    12.000000    15.000000
1         83.054136   15.000000   79.520000  ...   189.169186   260.323666
2        114.000000    8.333333   81.318182  ...    60.000000   162.000000
3         48.400000   13.250000   78.125000  ...    46.000000    82.000000
4         60.700000   15.000000  129.363636  ...   189.169186   260.323666
...             ...         ...         ...  ...          ...          ...
1469      64.000000   11.214286   86.260870  ...   189.169186   260.323666
1470      53.000000   13.000000   85.517241  ...    28.000000    35.000000
1471      75.000000    9.909091   91.147059  ...   189.169186   260.323666
1472      87.000000   10.833333  101.083333  ...   189.169186   260.323666
1473      87.400000    6.400000   91.785714  ...  1513.000000  1277.000000

      Max_Bilirubin.y  Max_Lactate.y  Max_Cholesterol.y  Max_TroponinI.y  \
0            0.200000       2.395461         156.842105         7.132683
1            1.979557       2.395461         156.842105         7.132683
2            0.400000       2.395461         212.000000         1.300000
3            0.300000       2.300000         156.842105         3.500000
4            1.979557       2.395461         156.842105         7.132683
...               ...            ...                ...              ...
1469         1.979557       2.395461         156.842105         7.132683
1470         0.900000       2.395461         156.842105         7.132683
1471         1.979557       2.395461         156.842105         7.132683
1472         1.979557       1.100000         156.842105         7.132683
1473         0.600000       1.900000         156.842105         7.132683

      Max_TroponinT.y  SAPS.I  SOFA  In.hospital_death
0            1.114629       7     1                  0
1            1.114629      17     2                  0
2            1.114629      14    11                  0
3            1.114629      19     8                  1
4            1.114629      11     0                  0
...               ...     ...   ...                ...
1469         1.114629       6     4                  0
1470         1.114629      19     8                  0
1471         1.114629      13     8                  0
1472         1.114629      19     7                  0
1473         1.114629      22    10                  1

[1474 rows x 232 columns]>

In [47]:
# Change Gender: Male = 1, Female = 0
ICU['Gender'] = ICU['Gender'].map({'male': 1, 'female': 0})

In [48]:
ICU['Gender'].value_counts(dropna=False)

Gender
NaN    1474
Name: count, dtype: int64

In [49]:
# Check missing value percentage for each column
missing_percentage = ICU.isna().mean() * 100
missing_percentage.sort_values(ascending=False)

Gender               100.0
RecordID               0.0
Min_NISysABP.y         0.0
Mean_ALT.y             0.0
Mean_AST.y             0.0
                     ...
Max_GCS.x              0.0
Max_HR.x               0.0
Max_NIDiasABP.x        0.0
Max_NIMAP.x            0.0
In.hospital_death      0.0
Length: 232, dtype: float64

In [50]:
# Find columns with more than 75% missing values
columns_above_75 = missing_percentage[missing_percentage > 75].index
columns_above_75.tolist()

['Gender']

In [51]:
# Remove columns with more than 75% missing values
ICU = ICU.drop(columns=columns_above_75)

In [60]:
# Check strange Height values
ICU[ICU['Height'] > 250]

,RecordID,Age,Height,ICUType2,ICUType3,ICUType4,Mean_Weight.x,Mean_GCS.x,Mean_HR.x,Mean_NIDiasABP.x,...,Max_ALT.y,Max_AST.y,Max_Bilirubin.y,Max_Lactate.y,Max_Cholesterol.y,Max_TroponinI.y,Max_TroponinT.y,SAPS.I,SOFA,In.hospital_death
165,133693,87,365.8,0,0,0,83.0541,14.0,59.0870,44.8000,...,189.1692,260.3237,0.7,2.3955,156.8421,7.1327,1.1146,12,2,0
1173,140479,50,419.1,0,0,0,67.6000,9.2,80.2632,63.7143,...,111.0000,168.0000,0.8,3.4000,205.0000,7.1327,1.1146,18,9,0

In [63]:
# Remove only unrealistic Height values, but keep missing values
ICU = ICU[(ICU['Height'] <= 250) | (ICU['Height'].isna())]

In [85]:
ICU['Height'].describe()

count    1472.000000
mean      168.933093
std         9.643186
min        13.700000
25%       169.787200
50%       169.787200
75%       169.787200
max       198.100000
Name: Height, dtype: float64

In [52]:
# Check duplicated rows
ICU.duplicated().sum()

np.int64(0)

In [53]:
# Remove duplicated rows
ICU = ICU.drop_duplicates()

In [54]:
# Check duplicated columns
duplicate_columns = ICU.T.duplicated()
ICU.columns[duplicate_columns].tolist()

['Min_MechVent.x',
 'Max_MechVent.x',
 'Mean_MechVent.y',
 'Min_MechVent.y',
 'Max_MechVent.y']

In [55]:
# Remove duplicated columns
ICU = ICU.loc[:, ~ICU.T.duplicated()]

In [56]:
# Check which numerical columns contain decimal values
numeric_columns = ICU.select_dtypes(include='number')

decimal_columns = [
    col for col in numeric_columns.columns
    if ((numeric_columns[col].dropna() % 1) != 0).any()
]

decimal_columns

['Height',
 'Mean_Weight.x',
 'Mean_GCS.x',
 'Mean_HR.x',
 'Mean_NIDiasABP.x',
 'Mean_NIMAP.x',
 'Mean_NISysABP.x',
 'Mean_RespRate.x',
 'Mean_Temp.x',
 'Mean_Urine.x',
 'Mean_BUN.x',
 'Mean_Creatinine.x',
 'Mean_Glucose.x',
 'Mean_HCO3.x',
 'Mean_GCT.x',
 'Mean_Mg.x',
 'Mean_Platelets.x',
 'Mean_K.x',
 'Mean_Na.x',
 'Mean_WBC.x',
 'Mean_pH.x',
 'Mean_PaCO2.x',
 'Mean_PaO2.x',
 'Mean_DiasABP.x',
 'Mean_FiO2.x',
 'Mean_MAP.x',
 'Mean_SysABP.x',
 'Mean_SaO2.x',
 'Mean_Albumin.x',
 'Mean_ALP.x',
 'Mean_ALT.x',
 'Mean_AST.x',
 'Mean_Bilirubin.x',
 'Mean_Lactate.x',
 'Mean_Cholesterol.x',
 'Mean_TroponinI.x',
 'Mean_TroponinT.x',
 'Min_Weight.x',
 'Min_GCS.x',
 'Min_HR.x',
 'Min_NIDiasABP.x',
 'Min_NIMAP.x',
 'Min_NISysABP.x',
 'Min_RespRate.x',
 'Min_Temp.x',
 'Min_Urine.x',
 'Min_BUN.x',
 'Min_Creatinine.x',
 'Min_Glucose.x',
 'Min_HCO3.x',
 'Min_GCT.x',
 'Min_Mg.x',
 'Min_Platelets.x',
 'Min_K.x',
 'Min_WBC.x',
 'Min_pH.x',
 'Min_PaCO2.x',
 'Min_PaO2.x',
 'Min_DiasABP.x',
 'Min_FiO2.x',
 'Min_MAP.x',
 'Min_SysABP.x',
 'Min_SaO2.x',
 'Min_Albumin.x',
 'Min_ALP.x',
 'Min_ALT.x',
 'Min_AST.x',
 'Min_Bilirubin.x',
 'Min_Lactate.x',
 'Min_Cholesterol.x',
 'Min_TroponinI.x',
 'Min_TroponinT.x',
 'Max_Weight.x',
 'Max_GCS.x',
 'Max_HR.x',
 'Max_NIDiasABP.x',
 'Max_NIMAP.x',
 'Max_NISysABP.x',
 'Max_RespRate.x',
 'Max_Temp.x',
 'Max_Urine.x',
 'Max_BUN.x',
 'Max_Creatinine.x',
 'Max_Glucose.x',
 'Max_HCO3.x',
 'Max_GCT.x',
 'Max_Mg.x',
 'Max_Platelets.x',
 'Max_K.x',
 'Max_Na.x',
 'Max_WBC.x',
 'Max_pH.x',
 'Max_PaCO2.x',
 'Max_PaO2.x',
 'Max_DiasABP.x',
 'Max_FiO2.x',
 'Max_MAP.x',
 'Max_SysABP.x',
 'Max_SaO2.x',
 'Max_Albumax.x',
 'Max_ALP.x',
 'Max_ALT.x',
 'Max_AST.x',
 'Max_Bilirubin.x',
 'Max_Lactate.x',
 'Max_Cholesterol.x',
 'Max_TroponinI.x',
 'Max_TroponinT.x',
 'Mean_Weight.y',
 'Mean_GCS.y',
 'Mean_HR.y',
 'Mean_NIDiasABP.y',
 'Mean_NIMAP.y',
 'Mean_NISysABP.y',
 'Mean_RespRate.y',
 'Mean_Temp.y',
 'Mean_Urine.y',
 'Mean_BUN.y',
 'Mean_Creatinine.y',
 'Mean_Glucose.y',
 'Mean_HCO3.y',
 'Mean_GCT.y',
 'Mean_Mg.y',
 'Mean_Platelets.y',
 'Mean_K.y',
 'Mean_Na.y',
 'Mean_WBC.y',
 'Mean_pH.y',
 'Mean_PaCO2.y',
 'Mean_PaO2.y',
 'Mean_DiasABP.y',
 'Mean_FiO2.y',
 'Mean_MAP.y',
 'Mean_SysABP.y',
 'Mean_SaO2.y',
 'Mean_Albumin.y',
 'Mean_ALP.y',
 'Mean_ALT.y',
 'Mean_AST.y',
 'Mean_Bilirubin.y',
 'Mean_Lactate.y',
 'Mean_Cholesterol.y',
 'Mean_TroponinI.y',
 'Mean_TroponinT.y',
 'Min_Weight.y',
 'Min_GCS.y',
 'Min_HR.y',
 'Min_NIDiasABP.y',
 'Min_NIMAP.y',
 'Min_NISysABP.y',
 'Min_RespRate.y',
 'Min_Temp.y',
 'Min_Urine.y',
 'Min_BUN.y',
 'Min_Creatinine.y',
 'Min_Glucose.y',
 'Min_HCO3.y',
 'Min_GCT.y',
 'Min_Mg.y',
 'Min_Platelets.y',
 'Min_K.y',
 'Min_Na.y',
 'Min_WBC.y',
 'Min_pH.y',
 'Min_PaCO2.y',
 'Min_PaO2.y',
 'Min_DiasABP.y',
 'Min_FiO2.y',
 'Min_MAP.y',
 'Min_SysABP.y',
 'Min_SaO2.y',
 'Min_Albumin.y',
 'Min_ALP.y',
 'Min_ALT.y',
 'Min_AST.y',
 'Min_Bilirubin.y',
 'Min_Lactate.y',
 'Min_Cholesterol.y',
 'Min_TroponinI.y',
 'Min_TroponinT.y',
 'Max_Weight.y',
 'Max_GCS.y',
 'Max_HR.y',
 'Max_NIDiasABP.y',
 'Max_NIMAP.y',
 'Max_NISysABP.y',
 'Max_RespRate.y',
 'Max_Temp.y',
 'Max_Urine.y',
 'Max_BUN.y',
 'Max_Creatinine.y',
 'Max_Glucose.y',
 'Max_HCO3.y',
 'Max_GCT.y',
 'Max_Mg.y',
 'Max_Platelets.y',
 'Max_K.y',
 'Max_Na.y',
 'Max_WBC.y',
 'Max_pH.y',
 'Max_PaCO2.y',
 'Max_PaO2.y',
 'Max_DiasABP.y',
 'Max_FiO2.y',
 'Max_MAP.y',
 'Max_SysABP.y',
 'Max_SaO2.y',
 'Max_Albumax.y',
 'Max_ALP.y',
 'Max_ALT.y',
 'Max_AST.y',
 'Max_Bilirubin.y',
 'Max_Lactate.y',
 'Max_Cholesterol.y',
 'Max_TroponinI.y',
 'Max_TroponinT.y']

In [58]:
ICU = ICU.round(4)

In [59]:
ICU.head()
ICU.shape
ICU.isna().sum()
ICU.duplicated().sum()

np.int64(0)

## 4. Executive Summary

Summarise key findings, major insights, and conclusions. Usually written after analysis is complete.

## 5. Data Loading

Describe the dataset(s), including size, format, and initial observations. Mention file paths or sources.

## 6. Data Cleaning

Explain how missing values, duplicates, and errors are handled. Include reasoning for any deletions, imputations, or corrections.

## 7. Preprocessing

Describe encoding of categorical variables, scaling or normalization of numerical features, and any other preparations for analysis or modeling.

## 8. Feature Engineering

Document any new variables created to enhance model performance or analysis, with reasoning.

## 9. Preliminary Analysis / Exploratory Data Analysis (EDA)

Visualise distributions, correlations, and patterns in the data. Identify relationships and trends relevant to your research questions.

## 10. Conclusions from EDA

Summarise the insights gained from EDA and how they guide further analysis or modeling.

## 11. Modeling / Analysis

Outline the predictive models or statistical analyses applied. Explain why each method was chosen and any evaluation strategy.

## 12. Model / Analysis Conclusions

Summarise model performance, key metrics, and interpretation. Discuss limitations or potential improvements.

## 13. Overall Conclusions

Answer your research questions based on findings. Summarise key insights, implications, and possible next steps.

## 14. Limitations

Document assumptions made during the project and any known limitations of the data, methodology, or analysis.

## 15. References

List sources, datasets, and literature cited in your report.

## Optional: Appendix